### ISSUE TITLE
桥接文件内容是空的怎么桥接的？

### ISSUE THREAD

**Issue by iScript** [6ag/microblog-swift#1]
看了一会儿的源码，请问你的microblog-swift-Bridging-Header.h桥接文件里面没写内容，是怎么做到桥接oc库的。
![2015-11-11 11 24 22](https://cloud.githubusercontent.com/assets/2595251/11083160/08a32422-8867-11e5-8605-2ebadf72e4d3.png)

还有打开后说资源文件没找到是为什么？
![2015-11-11 11 25 33](https://cloud.githubusercontent.com/assets/2595251/11083182/58941392-8867-11e5-8b25-d0d160509242.png)

swift新手。。。

**Comment by 6ag** [comment]
这里没有用到桥接，第三方都是用CocoaPods。资源文件你看看Resource目录下有没有

**Comment by iScript** [comment]
教程上说swift调用oc必须要一个桥接文件的。。 用cocoapods是如何做到swift调用oc那些库的？

**Comment by 6ag** [comment]
因为编译成framework了，直接在需要用的地方导入就行了

**Comment by iScript** [comment]
明白了，谢谢~
